### PR TITLE
[#155] Plugin should not log "Skipping Delombok" with WARN level

### PR DESCRIPTION
**Pull request by nils-christian**
Signed-off-by: Nils Christian Ehmke <nils-christian.ehmke@bmiag.de>

### CODE REVIEW

**Comment by pzygielo** [comment]
I would like to see that and 203 line changed as well.

**Review by awhitford — APPROVED** [review]
OK

**Comment by awhitford** [comment]
> I would like to see that and 203 line changed as well.

@pzygielo Why would you like this change on line 203?  I think my rationale was something along the lines of, _"Why would someone add the lombok-maven-plugin without a sourceDirectory? (They must have configured something wrong, so let's warn them.)"_

**Comment by lprimak** [comment]
@awhitford Let's say you have a multi-module project. Some modules have java sources, some don't.
Parent POM wants to declare lombok once (so no duplication is present in the POM file) i.e. DRY principle.
Currently, the modules with no source code will issue a WARN, which is not desired.

Thank you!

**Comment by pzygielo** [comment]
> Let's say you have a multi-module project. 

Yes, that!

For example `maven-compiler-plugin` ran against `<packaging>pom</packaging>` project:
```
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- maven-compiler-plugin:3.11.0:compile (default-cli) @ project ---
[INFO] No sources to compile
[INFO] ------------------------------------------------------------------------
```
No warning there.

**Pull request merged**
