### PR TITLE
Fix for issue 18

### PR DESCRIPTION
**Pull request by pdinc-oss**
see: https://github.com/awhitford/lombok.maven/issues/18

### CODE REVIEW

**Comment by GigabyteProductions** [comment]
Regarding CI: See #38

**Comment by pdinc-oss** [comment]
any updates?

**Comment by pzygielo** [comment]
> any updates?

I see some modifications on master were done to fix CI, yet your PR was not updated, and was not successfully processed by Travis.
Perhaps you could rebase @jpyeron's commit or merge master in.

**Comment by pdinc-oss** [comment]
The pull request is for https://github.com/awhitford/lombok.maven/commit/442905ce89ddc2ad7a4812ba267d4f4d6d12c36a

nothing to do with the CI related pushes (which are to mitigate a Jenkins issue)

Thank you.

**Comment by pdinc-oss** [comment]
The PR has been updated to f1344b8ed1f3e45cba925f1f047280eb0518173e, which merges 442905ce89ddc2ad7a4812ba267d4f4d6d12c36a. Please ignore the NON-master branches.

**Comment by awhitford** [comment]
Rather than adding `removeSourceDirectory` functionality, why not simply specify `false` for `addOutputDirectory`?  Would that not solve whatever your problem is?

**Comment by awhitford** [comment]
Unclear on why this is necessary, so closing it.

**Comment by pdinc-oss** [comment]
Seems the 2019 comment went to spam. Will provide the test scenario.

**Pull request closed without merging**
